# NumPy

NumPy is a first-rate library for numerical programming

* Widely used in academia, finance and industry
* Mature, fast, stable and under continuous development


## Introduction

The essential problem that NumPy solves is fast array processing

For example, suppose we want to create an array of 1 million random draws from a uniform distribution and compute the mean

If we did this in pure Python it would be orders of magnitude slower than C or Fortran

In NumPy this would be dealt with like this:

In [2]:
import numpy as np
x = np.random.uniform(0, 1, size=1000000)
x.mean()

0.4998486596270808

#### A Comment on Vectorization

NumPy is great for operations that are naturally vectorized

Vectorized operations are precompiled routines that can be sent in batches, like

* matrix multiplication and other linear algebra routines
* generating a vector of random numbers
* applying a fixed transformation (e.g., sine or cosine) to an entire array


## NumPy Arrays

The most important thing that NumPy defines is an array data type formally called a `numpy.ndarray`

To create a numpy array of only zeros:

In [4]:
z = np.zeros(3)

In [5]:
type(z)

numpy.ndarray

In [8]:
z

array([0., 0., 0.])

numpy arrays are like python lists except:

* The data must be homogenous - all elements of the same type
* The types must be one of the types (`dtypes`) provided by numpy

The most important ofthe `dtypes` are:

* int64
* float64
* bool

There are other dtypes representing complex numbers, unsigned integers, etc. google for it

The default for darray is `float64` 

In [7]:
type(z[0])

numpy.float64

If we want to for instance use integers instead of float:

In [10]:
a = np.zeros(3, dtype=int)

In [11]:
type(a[0])

numpy.int64

### Shape and Dimension

In [16]:
z = np.zeros(10)

In [17]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Here `z` is a flat array of no dimension - no row or column vector

We can use the attribute `shape` to see the dimensions:

In [18]:
z.shape

(10,)

Here the tuple only has one element, 10, which is the lenght of the array

To give it dimension, we can change the shape attibute 

In [19]:
z.shape = (10,1)

In [20]:
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [21]:
z.shape

(10, 1)

So now it has 10 rows, and 1 column

In [22]:
z.shape = (10,2)

ValueError: cannot reshape array of size 10 into shape (10,2)

So we can't give it a shape that doesn't make sense. Trying to make it a $10\times2$ matrix fails as there are only a total of 10 elements, not 20

In [24]:
z.shape= (2,5)

In [25]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
z = np.zeros(4)
z.shape = (2,2)

In [28]:
z

array([[0., 0.],
       [0., 0.]])

We could also have used the following, so that we don't have to reshape it:

In [29]:
z = np.zeros((2,2))

In [30]:
z

array([[0., 0.],
       [0., 0.]])

### Creating Arrays

We can also create ones and the identity matrix:

In [32]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [33]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

For identity, the parameter $n$ creates an $n\times n$ identity matrix

We can create an empty array in memory that can be populated later:

In [35]:
z = np.empty(3)

In [36]:
z

array([1.28822975e-231, 3.11109762e+231, 1.28822975e-231])

The values are garbarge - they represent whatever is in the memoery locations allocated.

We can also greate a grid of evenly spaced numbers:

In [37]:
np.linspace(2,4,5)

array([2. , 2.5, 3. , 3.5, 4. ])

So that creates an array starting at 2, ending at 4 that has a total of 5 values evenly spaced

We can also make arrays from Python datatypes (provdied they can be mapped to `dtypes`)

In [39]:
z = np.array([10,20])
z

array([10, 20])

In [40]:
type(z)

numpy.ndarray

We can also specify the type:

In [44]:
z = np.array([10,20], dtype=float)   ### float is equivalent to np.float64
z

array([10., 20.])

Multiple dimensions:

In [45]:
z = np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [46]:
z.shape

(2, 2)

There is also a function `np.asarray` that does not make a distinct copy of the data already in a NumPy array

In [49]:
na = np.linspace(2,4,5)
np.array(na)

array([2. , 2.5, 3. , 3.5, 4. ])

To check if it's copied or not:

In [50]:
na is np.array(na)

False

So a new copy was made.

In [51]:
na is np.asarray(na)

True

So if did not make a new copy

### Array Indexing

You can access elements in a flat array just like python

In [52]:
z = np.linspace(1,2,5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [53]:
z[0]

1.0

In [54]:
z[0:2]

array([1.  , 1.25])

In [55]:
z[-1]

2.0

For 2d arrays its similar:

In [56]:
z = np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [58]:
z[0,0]

1

In [59]:
z[0,1]

2

So its `array[row,column]` but slicing also can be applied

In [60]:
z[0,:]  # return the first row

array([1, 2])

In [61]:
z[1,:]

array([3, 4])

In [62]:
z[:,0]   # return the first column as an array 

array([1, 3])

In [64]:
z[:,:]  # obviously all the rows and columns

array([[1, 2],
       [3, 4]])

In [65]:
z[-1,:]   # last row

array([3, 4])

And so on

Numpy arrays or integers can also be used to extract data:

In [68]:
z = np.linspace(1,2,5)
i = np.array([0,1,3])
z[i]   # returns the 1s, 2nd and 4th elements

array([1.  , 1.25, 1.75])

the `dtype` `bool` can also be used:

In [70]:
d = np.array([0,1,1,0,1], dtype=bool)
d

array([False,  True,  True, False,  True])

In [72]:
z[d]   # the 2nd, 3rd and 5th elements

array([1.25, 1.5 , 2.  ])

All elements of an array can be set to the same value using slicing:

In [74]:
z = np.empty(5)
z[:] = 42

In [75]:
z

array([42., 42., 42., 42., 42.])

In [76]:
z[2:3] = 21

In [77]:
z

array([42., 42., 21., 42., 42.])

In [78]:
### Array Methods

In [79]:
a = np.array([4,3,2,1])

In [81]:
a.__dir__()

['__repr__',
 '__hash__',
 '__str__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__iter__',
 '__add__',
 '__radd__',
 '__sub__',
 '__rsub__',
 '__mul__',
 '__rmul__',
 '__mod__',
 '__rmod__',
 '__divmod__',
 '__rdivmod__',
 '__pow__',
 '__rpow__',
 '__neg__',
 '__pos__',
 '__abs__',
 '__bool__',
 '__invert__',
 '__lshift__',
 '__rlshift__',
 '__rshift__',
 '__rrshift__',
 '__and__',
 '__rand__',
 '__xor__',
 '__rxor__',
 '__or__',
 '__ror__',
 '__int__',
 '__float__',
 '__iadd__',
 '__isub__',
 '__imul__',
 '__imod__',
 '__ipow__',
 '__ilshift__',
 '__irshift__',
 '__iand__',
 '__ixor__',
 '__ior__',
 '__floordiv__',
 '__rfloordiv__',
 '__truediv__',
 '__rtruediv__',
 '__ifloordiv__',
 '__itruediv__',
 '__index__',
 '__matmul__',
 '__rmatmul__',
 '__imatmul__',
 '__len__',
 '__getitem__',
 '__setitem__',
 '__delitem__',
 '__contains__',
 '__new__',
 '__array__',
 '__array_prepare__',
 '__array_wrap__',
 '__array_ufunc__',
 '__sizeof__',
 '__copy__',
 '__deepcop

In [84]:
a.sort()   # Inplace sorting 
a

array([1, 2, 3, 4])

In [86]:
a.sum()     # Sum elements

10

In [87]:
a.mean()

2.5

In [88]:
a.max()

4

In [90]:
a.argmax()   # Returns index of maximal element

3

In [91]:
a.cumsum()   # Cumulative sum

array([ 1,  3,  6, 10])

In [92]:
a.cumprod()   # Cumulative product

array([ 1,  2,  6, 24])

In [93]:
a.var()   # Variance

1.25

In [94]:
a.std()   # std deviation

1.118033988749895

In [95]:
a.shape=(2,2)
a

array([[1, 2],
       [3, 4]])

In [96]:
a.T    # Transpost, equivalent to a.transpose()

array([[1, 3],
       [2, 4]])

In [100]:
a.transpose()

array([[1, 3],
       [2, 4]])

If `z` is nondecreasing array, then `z.searchsorted(a)` returns the index of the first element of `z` that is `>= a` 

In [103]:
z = np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [106]:
z.searchsorted(2.2)   # 2.5 is the first element that is >= 2.2

1

Many of the functions have equivalents in the numpy namespace:

In [107]:
a = np.array([4,3,2,1])
a

array([4, 3, 2, 1])

In [108]:
np.sort(a)     # not done in place

array([1, 2, 3, 4])

In [109]:
a

array([4, 3, 2, 1])

In [110]:
np.sum(a)

10

In [111]:
np.std(a)

1.118033988749895

and so on