# NumPy

NumPy is a first-rate library for numerical programming

* Widely used in academia, finance and industry
* Mature, fast, stable and under continuous development


## Introduction

The essential problem that NumPy solves is fast array processing

For example, suppose we want to create an array of 1 million random draws from a uniform distribution and compute the mean

If we did this in pure Python it would be orders of magnitude slower than C or Fortran

In NumPy this would be dealt with like this:

In [1]:
import numpy as np
x = np.random.uniform(0, 1, size=1000000)
x.mean()

0.49944977237712845

#### A Comment on Vectorization

NumPy is great for operations that are naturally vectorized

Vectorized operations are precompiled routines that can be sent in batches, like

* matrix multiplication and other linear algebra routines
* generating a vector of random numbers
* applying a fixed transformation (e.g., sine or cosine) to an entire array


## NumPy Arrays

The most important thing that NumPy defines is an array data type formally called a `numpy.ndarray`

To create a numpy array of only zeros:

In [2]:
z = np.zeros(3)

In [3]:
type(z)

numpy.ndarray

In [4]:
z

array([0., 0., 0.])

numpy arrays are like python lists except:

* The data must be homogenous - all elements of the same type
* The types must be one of the types (`dtypes`) provided by numpy

The most important ofthe `dtypes` are:

* int64
* float64
* bool

There are other dtypes representing complex numbers, unsigned integers, etc. google for it

The default for darray is `float64` 

In [5]:
type(z[0])

numpy.float64

If we want to for instance use integers instead of float:

In [6]:
a = np.zeros(3, dtype=int)

In [7]:
type(a[0])

numpy.int64

### Shape and Dimension

In [8]:
z = np.zeros(10)

In [9]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Here `z` is a flat array of no dimension - no row or column vector

We can use the attribute `shape` to see the dimensions:

In [10]:
z.shape

(10,)

Here the tuple only has one element, 10, which is the lenght of the array

To give it dimension, we can change the shape attibute 

In [11]:
z.shape = (10,1)

In [12]:
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [13]:
z.shape

(10, 1)

So now it has 10 rows, and 1 column

In [14]:
z.shape = (10,2)

ValueError: cannot reshape array of size 10 into shape (10,2)

So we can't give it a shape that doesn't make sense. Trying to make it a $10\times2$ matrix fails as there are only a total of 10 elements, not 20

In [15]:
z.shape= (2,5)

In [16]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
z = np.zeros(4)
z.shape = (2,2)

In [18]:
z

array([[0., 0.],
       [0., 0.]])

We could also have used the following, so that we don't have to reshape it:

In [19]:
z = np.zeros((2,2))

In [20]:
z

array([[0., 0.],
       [0., 0.]])

### Creating Arrays

We can also create ones and the identity matrix:

In [21]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

For identity, the parameter $n$ creates an $n\times n$ identity matrix

We can create an empty array in memory that can be populated later:

In [23]:
z = np.empty(3)

In [24]:
z

array([-2.00000000e+000, -3.11109492e+231, -2.00000000e+000])

The values are garbarge - they represent whatever is in the memoery locations allocated.

We can also greate a grid of evenly spaced numbers:

In [25]:
np.linspace(2,4,5)

array([2. , 2.5, 3. , 3.5, 4. ])

So that creates an array starting at 2, ending at 4 that has a total of 5 values evenly spaced

We can also make arrays from Python datatypes (provdied they can be mapped to `dtypes`)

In [26]:
z = np.array([10,20])
z

array([10, 20])

In [27]:
type(z)

numpy.ndarray

We can also specify the type:

In [28]:
z = np.array([10,20], dtype=float)   ### float is equivalent to np.float64
z

array([10., 20.])

Multiple dimensions:

In [29]:
z = np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [30]:
z.shape

(2, 2)

There is also a function `np.asarray` that does not make a distinct copy of the data already in a NumPy array

In [31]:
na = np.linspace(2,4,5)
np.array(na)

array([2. , 2.5, 3. , 3.5, 4. ])

To check if it's copied or not:

In [32]:
na is np.array(na)

False

So a new copy was made.

In [33]:
na is np.asarray(na)

True

So if did not make a new copy

### Array Indexing

You can access elements in a flat array just like python

In [34]:
z = np.linspace(1,2,5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [35]:
z[0]

1.0

In [36]:
z[0:2]

array([1.  , 1.25])

In [37]:
z[-1]

2.0

For 2d arrays its similar:

In [38]:
z = np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [39]:
z[0,0]

1

In [40]:
z[0,1]

2

So its `array[row,column]` but slicing also can be applied

In [41]:
z[0,:]  # return the first row

array([1, 2])

In [42]:
z[1,:]

array([3, 4])

In [43]:
z[:,0]   # return the first column as an array 

array([1, 3])

In [44]:
z[:,:]  # obviously all the rows and columns

array([[1, 2],
       [3, 4]])

In [45]:
z[-1,:]   # last row

array([3, 4])

And so on

Numpy arrays or integers can also be used to extract data:

In [46]:
z = np.linspace(1,2,5)
i = np.array([0,1,3])
z[i]   # returns the 1s, 2nd and 4th elements

array([1.  , 1.25, 1.75])

the `dtype` `bool` can also be used:

In [47]:
d = np.array([0,1,1,0,1], dtype=bool)
d

array([False,  True,  True, False,  True])

In [48]:
z[d]   # the 2nd, 3rd and 5th elements

array([1.25, 1.5 , 2.  ])

All elements of an array can be set to the same value using slicing:

In [49]:
z = np.empty(5)
z[:] = 42

In [50]:
z

array([42., 42., 42., 42., 42.])

In [51]:
z[2:3] = 21

In [52]:
z

array([42., 42., 21., 42., 42.])

In [53]:
### Array Methods

In [54]:
a = np.array([4,3,2,1])

In [55]:
a.__dir__()

['__repr__',
 '__hash__',
 '__str__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__iter__',
 '__add__',
 '__radd__',
 '__sub__',
 '__rsub__',
 '__mul__',
 '__rmul__',
 '__mod__',
 '__rmod__',
 '__divmod__',
 '__rdivmod__',
 '__pow__',
 '__rpow__',
 '__neg__',
 '__pos__',
 '__abs__',
 '__bool__',
 '__invert__',
 '__lshift__',
 '__rlshift__',
 '__rshift__',
 '__rrshift__',
 '__and__',
 '__rand__',
 '__xor__',
 '__rxor__',
 '__or__',
 '__ror__',
 '__int__',
 '__float__',
 '__iadd__',
 '__isub__',
 '__imul__',
 '__imod__',
 '__ipow__',
 '__ilshift__',
 '__irshift__',
 '__iand__',
 '__ixor__',
 '__ior__',
 '__floordiv__',
 '__rfloordiv__',
 '__truediv__',
 '__rtruediv__',
 '__ifloordiv__',
 '__itruediv__',
 '__index__',
 '__matmul__',
 '__rmatmul__',
 '__imatmul__',
 '__len__',
 '__getitem__',
 '__setitem__',
 '__delitem__',
 '__contains__',
 '__new__',
 '__array__',
 '__array_prepare__',
 '__array_wrap__',
 '__array_ufunc__',
 '__sizeof__',
 '__copy__',
 '__deepcop

In [56]:
a.sort()   # Inplace sorting 
a

array([1, 2, 3, 4])

In [57]:
a.sum()     # Sum elements

10

In [58]:
a.mean()

2.5

In [59]:
a.max()

4

In [60]:
a.argmax()   # Returns index of maximal element

3

In [61]:
a.cumsum()   # Cumulative sum

array([ 1,  3,  6, 10])

In [62]:
a.cumprod()   # Cumulative product

array([ 1,  2,  6, 24])

In [63]:
a.var()   # Variance

1.25

In [64]:
a.std()   # std deviation

1.118033988749895

In [65]:
a.shape=(2,2)
a

array([[1, 2],
       [3, 4]])

In [66]:
a.T    # Transpost, equivalent to a.transpose()

array([[1, 3],
       [2, 4]])

In [67]:
a.transpose()

array([[1, 3],
       [2, 4]])

If `z` is nondecreasing array, then `z.searchsorted(a)` returns the index of the first element of `z` that is `>= a` 

In [68]:
z = np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [69]:
z.searchsorted(2.2)   # 2.5 is the first element that is >= 2.2

1

Many of the functions have equivalents in the numpy namespace:

In [70]:
a = np.array([4,3,2,1])
a

array([4, 3, 2, 1])

In [71]:
np.sort(a)     # not done in place

array([1, 2, 3, 4])

In [72]:
a

array([4, 3, 2, 1])

In [73]:
np.sum(a)

10

In [74]:
np.std(a)

1.118033988749895

and so on

### Operations on arrays

#### Arithmetic operations

The arithmitic operators, `+`, `-`, '/', `*` and `**` act *elementwise* on arrays

In [75]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [76]:
a + b

array([ 6,  8, 10, 12])

In [77]:
a * b

array([ 5, 12, 21, 32])

In [78]:
a + 10

array([11, 12, 13, 14])

In [79]:
a * 10

array([10, 20, 30, 40])

2D arrays work in a similar way

In [80]:
a = np.ones((2,2))
b = np.ones((2,2))

In [81]:
a + b

array([[2., 2.],
       [2., 2.]])

In [82]:
 a - b

array([[0., 0.],
       [0., 0.]])

In [83]:
a * b

array([[1., 1.],
       [1., 1.]])

`A * B` is not the matrix product, it is an element-wise product

#### Matrix Multiplication

In [84]:
A = np.ones((2,2))
B = np.ones((2,2))

In [85]:
A @ B

array([[2., 2.],
       [2., 2.]])

That was the dot product ${A}\cdot {B}$

In older version of python, `np.dot` functions should be used

In [86]:
np.dot(A,B)

array([[2., 2.],
       [2., 2.]])

We can also use `@` to take the dot product of two flat arrays

In [87]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a @ b   # should be 1*4 + 2*5 + 3*6 = 32

32

We can also use `@` when one element is a python list or tuple

In [88]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [89]:
b = A @ (0,1)
b

array([2, 4])

In [90]:
b.shape

(2,)

Since we are postmultiplying, the tuple is treated as a column vector, however the result is not a column vector, it is a flat array. For proper a proper column vector result we actually need to take the dot product of two arrays, as in ${n \times m} \cdot {m \times 1} = {n \times 1}$

That would be:

In [91]:
A = np.array([[1,2],[3,4],[4,5]])   # 3 x 2
A.shape

(3, 2)

In [92]:
B = np.array([0,1])
B.shape = (2,1)  # 2 x 1
B    

array([[0],
       [1]])

In [93]:
c = A @ B   # 3 x 1
c

array([[2],
       [4],
       [5]])

In [94]:
c.shape

(3, 1)

### Mutability and copying Arrays

NumPy arrays are mutable datatypes, like Python lists

i.e. their contents can be mutated/altered in memery after initialization


In [95]:
a = [1,2,3]
b = a
b[1] =3
a


[1, 3, 3]

Freaky so we changed a by changing b.... Let see that work for NumPy arrays

In [96]:
a = np.array([2,4])
a

array([2, 4])

In [97]:
a[-1] = 0
a

array([2, 0])

In [98]:
a = np.random.randn(3)
a

array([ 1.04636684,  0.44885837, -1.34065831])

In [99]:
b = a
b[0] = 0
a

array([ 0.        ,  0.44885837, -1.34065831])

So, once again we changed a by changing b

What's going on here? 

The name `b` is bound to `a` and just becomes another reference to the array

This means that we pass around pointers to data rather than making copies, so `a` and `b` both reference the same pointer



#### Making copies

It is possible to make an independant copy of `a` if required

In recent versions of NumPy it's best to use the `np.copyto` function

In [100]:
a = np.random.randn(3)
a

array([ 0.80475631,  1.297032  , -1.01083432])

In [101]:
b = np.empty_like(a)   # make an empty array that looks like a
np.copyto(b,a)
b

array([ 0.80475631,  1.297032  , -1.01083432])

Now b is an independant (deep) copy of a

In [102]:
b[0] = 0
b

array([ 0.        ,  1.297032  , -1.01083432])

In [103]:
a

array([ 0.80475631,  1.297032  , -1.01083432])

## Additional Functionality

### Vectorized Functions

NumPy provides vectorized versions of the standard functions `log`,`exp`, `sin`, etc. that act *element-wise* on arrays

In [104]:
z = np.array([1,2,3])
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

This means we dont need to write something like this to do our own element-wise methods:

In [105]:
n = len(z)
y = np.empty(n)
for i in range(n):
    y[i] = np.sin(z[i])

In [106]:
y

array([0.84147098, 0.90929743, 0.14112001])

Because they act element-wise on arrays, these functions are called *vectorized functions*

In NumPy-speak, they are also called *ufuncs*, which stands for “universal functions”

As we say earlier, the arithmetic operators also work element-waise, so combining them with ufuncs give a very rich set of fast element-wise functions 

In [107]:
z

array([1, 2, 3])

In [108]:
(1 /np.sqrt(2 * np.pi)) * np.exp(-0.5 * z**2)

array([0.24197072, 0.05399097, 0.00443185])

So we applied ${1 \over \sqrt {2 \pi}} e ^ {-{1 \over 2} {z_i}^2}$ to each element ${z_i}$ of the array $z$

Not all user defined functions will act element-wise. For example the function below will fail if passed in an array

In [109]:
def f(x):
    return 1 if x>0 else 0

In [110]:
f(z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The function `np.where` provides an alternative:

In [111]:
z = np.random.randn(4)
z

array([-0.67882513, -0.18999374, -1.74841489,  0.09495533])

In [112]:
np.where(z >0, 1, 0)   # Insert 1 if element > 0, otherwise 0

array([0, 0, 0, 1])

You can also use `np.vectorize` to vectorize a user function, but beware, it may not vectorize well and might be slower than an element-wise version as per above user function

In [113]:
f = np.vectorize(f)
f(z)

array([0, 0, 0, 1])

### Comparisons

As a rule, comparisons are done element-wise

In [114]:
x = np.array([2,3])
y = np.array([2,3])
x == y

array([ True,  True])

In [115]:
y[0] = 1
x == y

array([False,  True])

In [116]:
x != y

array([ True, False])

For `>`, `<`, `>=`, and `<=` is similar

In [117]:
z = np.linspace(0,10,5)
z

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [118]:
z > 3

array([False, False,  True,  True,  True])

This is useful for conditional extraction 

In [119]:
b = z > 3
b

array([False, False,  True,  True,  True])

In [120]:
z[b]

array([ 5. ,  7.5, 10. ])

This can also be done in one step:

In [121]:
z[z > 3]

array([ 5. ,  7.5, 10. ])

## Exercises

### Exercise 1

Consider the polynomial expression
(1)
$$p(x)=a_0+a_1x+a_2x^2+⋯a_nx_n= \sum_{n=1}^{n}a_ix^i$$

Earlier, we wrote a simple function `p(x, coeff)` to evaluate (1) without considering efficiency

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop

(Such functionality is already implemented as `np.poly1d`, but for the sake of the exercise don’t use this class)

* Hint: Use `np.cumprod()`


In [129]:
import numpy as np

def p(x, coeff):
    xs = np.empty(len(coeff))
    xs[0] = 1
    xs[1:] = x
    xpower = xs.cumprod()
    return coeff @ xpower
    


In [154]:
coeff = np.array([1,2,3])
print(p(5, coeff))   ### Equivalent to 1 + 2x + 3x^2

### For comparison, check again np.ploy1d
### Caveat - for poly1d, the coeffecients are in decreasing powers, so we need to reverse them

rev_coeff = coeff[::-1]     ### [::-1] reverses an array
q = np.poly1d(rev_coeff)
print(q)
print(q(5))

86.0
   2
3 x + 2 x + 1
86


### Exercise 2

Let `q` be a NumPy array of length `n` with `q.sum() == 1`

Suppose that `q` represents a probability mass function

We wish to generate a discrete random variable `x`
such that $P\{x=i\}=q_i$

In other words, `x` takes values in `range(len(q))` and `x = i` with probability `q[i]`

The standard (inverse transform) algorithm is as follows:

* Divide the unit interval [0,1] into $n$ subintervals $I_0,I_1,…,I_{n−1}$ such that the length of $I_i$ is $q_i$
* Draw a uniform random variable $U$ on [0,1] and return the $i$ such that $U \in {I_i}$

The probability of drawing $i$ is the length of $I_i$, which is equal to $q_i$

We can implement the algorithm as follows

```python
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]
```

Your exercise is to speed it up using NumPy, avoiding explicit loops

* Hint: Use `np.searchsorted` and `np.cumsum`

If you can, implement the functionality as a class called `discreteRV`, where

* the data for an instance of the class is the vector of probabilities `q`
* the class has a `draw()` method, which returns one draw according to the algorithm described above

If you can, write the method so that `draw(k)` returns `k` draws from `q`

In [206]:
from random import uniform
import numpy as np

def sample(q):
    U = uniform(0,1)
    cumsum = np.cumsum(q)
    return cumsum.searchsorted(U)

q = np.array([0.25, 0.75])
sample(q)    

0

In [211]:
import numpy as np
from numpy import cumsum
from numpy.random import uniform

class DiscreteRV:
    """
    Generates an array of draws from a discrete random variable with vector of
    probabilities given by q.
    """
    
    def __init__(self,q):
        """
        The argument q is a NumPy array, or array like, nonnegative and sums
        to 1
        """ 
        self.q = q
        self.Q = np.cumsum(q)   ## np.cumsum(q)
        
    def draw(self, k=1):
        """
        Returns k draws from q. For each such draw, the value i is returned
        with probability q[i].
        """
        U = uniform(0,1, size=k)
        return self.Q.searchsorted(U)
    

In [212]:
q = (0.25, 0.75)
d = DiscreteRV(q)

In [213]:
d.draw(5)

array([0, 1, 0, 1, 1])

In [214]:
for i in range(5):
    print(sample(np.array(q)))

0
1
0
1
0
